name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.10.2-slim

    services:
      db:
        image: postgres:13.1
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build/dev
            _build/test
          key: elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-${{github.ref}}
          restore-keys: |
            elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-${{hashFiles('mix.lock')}}-
            elixir-cache-${{secrets.CACHE_VERSION}}-${{matrix.elixir}}-otp-${{matrix.otp}}-${{runner.os}}-

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Test
        env:
          MIX_ENV: test
          DATABASE_URL: postgres://postgres:postgres@db:5432/workbench_?
          SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}
          LIVE_VIEW_SIGNING_SALT: ${{secrets.LIVE_VIEW_SIGNING_SALT}}
          GUARDIAN_SECRET_KEY: ${{secrets.GUARDIAN_SECRET_KEY}}
        run: |
          mix ecto.create
          mix ecto.migrate
          mix test

      - name: Dialyzer
        run: mix dialyzer --halt-exit-status
